on: [push]

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    name: A demo job to delete workflow runs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete COMPLETED workflow runs older than 12hrs
        uses: ./ # Uses an action in the root directory
        id: delete-old-workflow-runs-completed
        with:
          repository: MajorScruffy/delete-old-workflow-runs
          workflow: ".github/workflows/main.yml"
          older-than-seconds: 34200
          # created-before: "2021-12-08T16:34:00Z"
          # actor: test@test.com
          # branch: main
          # event: push
          event: completed
          # what-if: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete ALL workflow runs older than 2d
        uses: ./ # Uses an action in the root directory
        id: delete-old-workflow-runs-all
        with:
          repository: MajorScruffy/delete-old-workflow-runs
          workflow: ".github/workflows/main.yml"
          older-than-seconds: 14400
          # created-before: "2021-12-08T16:34:00Z"
          # actor: test@test.com
          # branch: main
          # event: push
          # event: completed
          # what-if: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}